<a href="https://colab.research.google.com/github/Ahmed-Waleed345/Project-1/blob/main/Project1_DataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Loading data

In [92]:
import pandas as pd

# Use a raw string for the Windows path to avoid accidental escape sequences
df = pd.read_excel(r'/content/Dataset for Data Analytics.xlsx')

df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

Knowing information about the data

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

# **Phase 1: Handling missing values**

In [84]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [85]:
df['CouponCode'] = df['CouponCode'].fillna('No Coupon')

# checking null values after handling missed values
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

# Phase 2: Handling duplicates

I have checked 'OrderID' column since it must be unique, in addition of checking the duplicate rows

In [86]:
print("No. of duplicate rows:", df['OrderID'].nunique())
# duplicates in OrderID column
df.duplicated(subset=['OrderID']).sum()

No. of duplicate rows: 1200

np.int64(0)

In [87]:
# repeated rows
df.duplicated().sum()

np.int64(0)

# **Phase 3: Speak One Language**

Checking date formats by checking 'Date' column datatype and if it is object, then there may be errors in formating, else, pandas has recognized that the data type of 'Date' is something with [ns]

In [88]:
df['Date'].dtype

dtype('<M8[ns]')

Ensuring that No invalid date formats are there in the dataset

In [89]:
## this line isn't needed as we have already checked for Null values in the data
# print("No. of invalid dates:", df['Date'].isna().sum())

# Converting Date column format into ISO 8601
df['Date'] = df['Date'].dt.strftime('%Y-%m-%d')

No. of invalid dates: 0

Stripping text columns

In [90]:
# Removing any extra spaces in OrderID column
df['OrderID'] = df['OrderID'].astype(str).str.strip().str.upper()

# Removing any extra spaces in the object type columns
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].astype(str).str.strip()